### ISSUE TITLE
Create a relationship between mentors and mentees

### ISSUE THREAD

**Issue by Renwarren** [PkFokam-Alumni-Network/CommunityBackendService#14]
Evolve the alumni/users schema to make a relationship between mentors and mentees.
The relationship is 1 mentor can have 1+ mentees but 1 mentee can have 1 mentor.

**Comment by bjoelfra** [comment]
Based on:
1. A user can either be a mentor or not
2. A mentor can have several mentees, but each mentee can only have one mentor
3. If a user is not a mentor, deleting the user should not affect a database
4. If a mentor is deleted, it might affect the mentor under them.
Assuming we have a data model design:
**Each user is automatically assigned a mentor, the mentor can point to null in case where the user has no mentor**
Users-table:
email: (primary-key)
name:
is_mentor: True or False
others: .....
Mentors table:
mentor_email: (foreign_key)
mentee's_email: (foreign_key)

In case of deletion of a user who is not a mentor, deletion can be done straight forward. If the user to be deleted is a mentor we can assign the mentees under him back to Null and delete him without it affecting our db.
Other question: Can a mentor also have a mentor ? Probably not what do you think ? Also will I work on the db part or just adjust the users schema.

**Comment by Renwarren** [comment]
Some adjustments here:
- Instead of having two tables, let's continue with one table. We can have a mentorEmail as an attribute which will have the mentor's email and we can use null if that person does not have a mentor.c

2. A mentor can also have a mentor, let's think about the example where: Joel just started work but he is the mentor of Yann who is still in school. At the same time, Marcel who has 3 years of experience can also mentor Joel. We therefore have Marcel mentors Joel who mentors Yann. 

3. Adjust the data model and the schemas. What is in the models folder is what is contained in the database, the schemas are used as input and output when interacting with our database.

4.  Add tests to consider the deletion of a mentor from the database and see the effect on a mentee. Try to do a test for a mentor who has two mentees.
